import { Oswald } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";

const oswald = Oswald({ subsets: ["latin"], weight: ["200", "300", "400", "500", "600", "700"] });

export const metadata = {
  title: "WAC Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.className}`}>
        {/* --LENIS SMOOTH SCROLL--- */}
        <SmoothScroll>
        {children}
        </SmoothScroll>
        </body>
    </html>
  );
}
